#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/vhdldep
#-------------------------------------------------------------------------------

echo 'copying files'
mkdir -p "$HOME/.local/bin/" &&
cp src/vhdldep "$HOME/.local/bin/"
