#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/vhdldep
#-------------------------------------------------------------------------------

echo 'copying files'
mkdir -p /usr/local/bin/ &&
cp src/vhdldep /usr/local/bin/
