#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/vhdldep
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f "$HOME/.local/bin/vhdldep"
